tic;

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/bochum/',...
    'disparity/train/bochum/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/bochum/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/bochum/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/bremen/',...
    'disparity/train/bremen/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/bremen/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/bremen/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/cologne/',...
    'disparity/train/cologne/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/cologne/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/cologne/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/darmstadt/',...
    'disparity/train/darmstadt/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/darmstadt/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/darmstadt/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/dusseldorf/',...
    'disparity/train/dusseldorf/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/dusseldorf/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/dusseldorf/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/erfurt/',...
    'disparity/train/erfurt/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/erfurt/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/erfurt/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/hamburg/',...
    'disparity/train/hamburg/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/hamburg/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/hamburg/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/hanover/',...
    'disparity/train/hanover/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/hanover/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/hanover/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/jena/',...
    'disparity/train/jena/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/jena/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/jena/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/krefeld/',...
    'disparity/train/krefeld/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/krefeld/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/krefeld/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/monchengladbach/',...
    'disparity/train/monchengladbach/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/monchengladbach/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/monchengladbach/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/strasbourg/',...
    'disparity/train/strasbourg/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/strasbourg/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/strasbourg/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/stuttgart/',...
    'disparity/train/stuttgart/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/stuttgart/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/stuttgart/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/tubingen/',...
    'disparity/train/tubingen/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/tubingen/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/tubingen/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/ulm/',...
    'disparity/train/ulm/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/ulm/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/ulm/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/weimar/',...
    'disparity/train/weimar/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/weimar/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/weimar/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/train/zurich/',...
    'disparity/train/zurich/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/train/zurich/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/train/zurich/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/val/frankfurt/',...
    'disparity/val/frankfurt/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/val/frankfurt/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/val/frankfurt/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/val/lindau/',...
    'disparity/val/lindau/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/val/lindau/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/val/lindau/');

Haze_simulation('/srv/glusterfs/daid/data/cityscape/', 'leftImg8bit/val/munster/',...
    'disparity/val/munster/',...
    '/srv/glusterfs/csakarid/data/Cityscapes/camera_trainvaltest/camera/val/munster/',...
    '/scratch_net/nowin/csakarid/Code/Deep_learning/Toyota-foggy/data/Cityscapes/leftImg8bit_trainvaltest-hazy-depth_missing/val/munster/');

toc;